import type { Metadata } from 'next'
import Link from 'next/link'
import KnowledgeCard from '@/components/oraculo/KnowledgeCard'
import { categories, entries, SITE_URL } from '@/lib/oraculo'

export const metadata: Metadata = { title: 'ORÁCULO — Hub de Conhecimento Financeiro | Zafi', description: 'Respostas claras, verificadas e conectadas para negociar dívidas e tomar decisões melhores.', alternates: { canonical: '/oraculo' }, openGraph: { type: 'website', url: '/oraculo', title: 'ORÁCULO — Hub de Conhecimento da Zafi', description: 'Conhecimento estruturado para entender dívidas e decidir com segurança.' }, twitter: { card: 'summary_large_image', title: 'ORÁCULO — Zafi', description: 'Respostas claras e verificadas para sua vida financeira.' } }

export default function Page() {
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'CollectionPage', '@id': `${SITE_URL}/oraculo#webpage`, name: 'ORÁCULO — Hub de Conhecimento Financeiro', url: `${SITE_URL}/oraculo` }, { '@type': 'ItemList', numberOfItems: entries.length, itemListElement: entries.map((entry, index) => ({ '@type': 'ListItem', position: index + 1, name: entry.title, url: `${SITE_URL}/oraculo/${entry.category}/${entry.slug}` })) }] }
  return <main className="min-h-screen bg-[#f6f8fc] text-slate-950"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <header className="border-b border-blue-100 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/" className="text-xl font-black text-blue-700">Zafi</Link><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold uppercase tracking-widest text-blue-700">Projeto ORÁCULO</span></div></header>
    <section className="border-b border-blue-100 bg-[radial-gradient(circle_at_top_right,_#dbeafe,_transparent_42%)]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 md:grid-cols-[1.35fr_.65fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.2em] text-blue-700">Conhecimento que orienta</p><h1 className="mt-4 text-4xl font-black leading-[1.08] tracking-tight sm:text-6xl">A resposta certa antes da próxima decisão financeira.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Uma biblioteca clara, revisada e construída para ajudar — não para empurrar ofertas.</p></div><aside className="self-end rounded-3xl border border-blue-200 bg-white/90 p-6 shadow-xl shadow-blue-900/5"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Coleção inicial</p><p className="mt-3 text-5xl font-black text-blue-700">{entries.length}</p><p className="font-bold">respostas-modelo</p><p className="mt-4 text-sm leading-6 text-slate-600">Com fontes, revisão, FAQs e caminhos relacionados.</p></aside></div></section>
    <div className="mx-auto max-w-6xl px-5 py-14"><section><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Índice por assunto</p><h2 className="mt-2 text-3xl font-black">Explore as estantes</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category) => { const count = entries.filter((entry) => entry.category === category.slug).length; return <Link key={category.slug} href={`/oraculo/${category.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-5 hover:border-blue-300 hover:shadow-md"><div className="flex justify-between"><span className="text-2xl" aria-hidden="true">{category.icon}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{count}</span></div><h3 className="mt-4 text-lg font-extrabold group-hover:text-blue-700">{category.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{category.description}</p></Link> })}</div></section>
    <section className="mt-16"><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Coleção inicial</p><h2 className="mt-2 text-3xl font-black">Respostas essenciais</h2><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{entries.map((entry) => <KnowledgeCard key={entry.slug} entry={entry} />)}</div></section>
    <section className="mt-16 rounded-3xl bg-slate-950 p-8 text-white md:flex md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Método Zafi</p><h2 className="mt-2 text-2xl font-black">Resposta direta. Contexto. Próximo passo.</h2><p className="mt-3 text-sm text-slate-300">Orientação editorial separada de recomendação comercial.</p></div><Link href="/" className="mt-6 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold md:mt-0">Fazer diagnóstico gratuito</Link></section></div>
  </main>
}
