import type { ContentFactoryPilot } from './types'

const reviewedAt = '2026-07-24T09:30:00-03:00'

export const contentFactoryPilots: ContentFactoryPilot[] = [
  {
    id: 'oe008-institucional-v1',
    kind: 'institutional',
    themeId: 'zafi-entender-antes-de-decidir',
    title: 'Antes de decidir, entenda',
    topic: 'O papel da Zafi na jornada de quem está endividado',
    objective: 'Apresentar a Zafi como diagnóstico e orientação, não como vitrine de ofertas.',
    audience: 'Pessoas endividadas que ainda não sabem por onde começar.',
    durationSeconds: 28,
    status: 'pending_approval',
    stage: 'pending_approval',
    score: 94,
    hooks: [
      'Dívida não se resolve no impulso.',
      'Antes de aceitar qualquer proposta, entenda sua situação.',
      'Você não precisa decidir tudo hoje.',
    ],
    selectedHook: 'Antes de aceitar qualquer proposta, entenda sua situação.',
    spokenText:
      'Antes de aceitar qualquer proposta, entenda sua situação. A Zafi organiza suas dívidas, mostra o que merece prioridade e cria um plano simples para o próximo passo. Sem prometer atalhos e sem empurrar ofertas. Comece pelo diagnóstico financeiro gratuito da Zafi.',
    ctas: [
      'Faça o diagnóstico financeiro gratuito da Zafi.',
      'Entenda sua situação antes de escolher o próximo passo.',
    ],
    selectedCta: 'Faça o diagnóstico financeiro gratuito da Zafi.',
    caption:
      'Organizar vem antes de decidir. A Zafi ajuda você a enxergar prioridades e próximos passos com clareza.',
    description:
      'Vídeo institucional da Zafi sobre diagnóstico financeiro responsável e orientação para pessoas endividadas.',
    hashtags: ['#Zafi', '#OrganizaçãoFinanceira', '#Dívidas', '#EducaçãoFinanceira'],
    thumbnailText: 'Entenda antes de decidir',
    thumbnailUrls: [
      '/content-factory/oe-008/institucional/thumbnail-a.svg',
      '/content-factory/oe-008/institucional/thumbnail-b.svg',
      '/content-factory/oe-008/institucional/thumbnail-c.svg',
    ],
    editStyles: ['Editorial calmo', 'Tipografia cinética'],
    scenes: [
      { kicker: 'ZAFI / DIAGNÓSTICO', title: 'Antes de decidir, entenda.', body: 'Decisão financeira não precisa nascer do impulso.', durationMs: 5000, treatment: 'ink' },
      { kicker: 'PASSO 01', title: 'Organize suas dívidas', body: 'Veja valores, tipos e prioridades em um só lugar.', durationMs: 5500, treatment: 'light' },
      { kicker: 'PASSO 02', title: 'Enxergue o que pesa mais', body: 'Juros e urgência mudam a ordem das decisões.', durationMs: 5500, treatment: 'blue' },
      { kicker: 'SEM ATALHOS', title: 'Orientação, não pressão', body: 'Sem promessa fácil. Sem oferta empurrada.', durationMs: 5500, treatment: 'signal' },
      { kicker: 'PRÓXIMO PASSO', title: 'Diagnóstico gratuito', body: 'Comece com clareza em meuzafi.com.br', durationMs: 6000, treatment: 'ink' },
    ],
    direction: {
      emotion: 'Acolhimento seguro',
      pace: 'Calmo, 135 palavras por minuto',
      pauses: 'Pausa curta após cada orientação',
      framing: 'Plano médio, câmera na altura dos olhos',
      expression: 'Serena, sem euforia comercial',
      voice: 'Pt-BR neutra, clara e próxima',
    },
    provider: { id: 'local-motion-v1', label: 'Zafi Motion Preview', generationTimeMs: 180, estimatedCostBrl: 0 },
    quality: { clarity: 97, retention: 90, branding: 98, cta: 94, spelling: 100, visual: 92, accessibility: 95 },
    compliance: { status: 'approved', findings: [], reviewedAt },
    trace: { researchId: 'oe008-research-001', briefId: 'oe008-brief-institucional', scriptVersion: 1, assetVersion: 1 },
  },
  {
    id: 'oe008-educacional-v1',
    kind: 'educational',
    themeId: 'qual-divida-pagar-primeiro',
    title: 'Qual dívida pagar primeiro?',
    topic: 'Critérios práticos para ordenar dívidas',
    objective: 'Ensinar uma regra simples e levar ao diagnóstico sem prometer resultado.',
    audience: 'Pessoas com duas ou mais dívidas e pouca clareza de prioridade.',
    durationSeconds: 30,
    status: 'pending_approval',
    stage: 'pending_approval',
    score: 96,
    hooks: [
      'A menor dívida nem sempre deve ser paga primeiro.',
      'Se você tem várias dívidas, não escolha pelo susto.',
      'Quer saber qual dívida merece prioridade?',
    ],
    selectedHook: 'A menor dívida nem sempre deve ser paga primeiro.',
    spokenText:
      'A menor dívida nem sempre deve ser paga primeiro. Comece olhando três coisas: juros, risco de perder um serviço essencial e impacto no seu orçamento. Cartão e cheque especial costumam crescer rápido, mas cada caso é diferente. A Zafi organiza essas informações para você. Faça o diagnóstico financeiro gratuito.',
    ctas: [
      'Faça o diagnóstico financeiro gratuito da Zafi.',
      'Organize suas dívidas e descubra sua próxima prioridade.',
    ],
    selectedCta: 'Organize suas dívidas e descubra sua próxima prioridade.',
    caption:
      'Valor pequeno não significa custo pequeno. Juros, urgência e impacto no orçamento ajudam a definir a prioridade.',
    description:
      'Conteúdo educativo com três critérios para organizar a ordem de pagamento das dívidas.',
    hashtags: ['#Dívidas', '#CartãoDeCrédito', '#FinançasPessoais', '#Zafi'],
    thumbnailText: 'Qual pagar primeiro?',
    thumbnailUrls: [
      '/content-factory/oe-008/educacional/thumbnail-a.svg',
      '/content-factory/oe-008/educacional/thumbnail-b.svg',
      '/content-factory/oe-008/educacional/thumbnail-c.svg',
    ],
    editStyles: ['Lista visual em três critérios', 'Comparação com cartões'],
    scenes: [
      { kicker: 'MITO', title: 'A menor nem sempre vem primeiro', body: 'O valor sozinho não mostra o peso da dívida.', durationMs: 5500, treatment: 'signal' },
      { kicker: 'CRITÉRIO 01', title: 'Juros', body: 'Quanto mais rápido cresce, mais atenção merece.', durationMs: 5500, treatment: 'blue' },
      { kicker: 'CRITÉRIO 02', title: 'Urgência', body: 'Proteja moradia e serviços essenciais.', durationMs: 5500, treatment: 'light' },
      { kicker: 'CRITÉRIO 03', title: 'Orçamento', body: 'A parcela precisa caber na vida real.', durationMs: 5500, treatment: 'ink' },
      { kicker: 'ORGANIZE', title: 'Descubra sua prioridade', body: 'Diagnóstico gratuito em meuzafi.com.br', durationMs: 8000, treatment: 'blue' },
    ],
    direction: {
      emotion: 'Didática e respeitosa',
      pace: 'Objetivo, 145 palavras por minuto',
      pauses: 'Pausa marcada entre os três critérios',
      framing: 'Plano médio com cards laterais',
      expression: 'Atenta e encorajadora',
      voice: 'Pt-BR neutra, tom de consultoria',
    },
    provider: { id: 'local-motion-v1', label: 'Zafi Motion Preview', generationTimeMs: 210, estimatedCostBrl: 0 },
    quality: { clarity: 99, retention: 95, branding: 96, cta: 95, spelling: 100, visual: 94, accessibility: 96 },
    compliance: { status: 'approved', findings: [], reviewedAt },
    trace: { researchId: 'oe008-research-002', briefId: 'oe008-brief-educacional', scriptVersion: 1, assetVersion: 1 },
  },
  {
    id: 'oe008-viral-v1',
    kind: 'viral',
    themeId: 'divida-pequena-juros-grandes',
    title: 'A dívida pequena que cresce escondida',
    topic: 'O efeito dos juros sobre dívidas aparentemente pequenas',
    objective: 'Gerar atenção e compartilhamento com utilidade, sem alarmismo.',
    audience: 'Pessoas que adiam dívidas pequenas de cartão ou limite da conta.',
    durationSeconds: 24,
    status: 'pending_approval',
    stage: 'pending_approval',
    score: 91,
    hooks: [
      'Essa dívida pequena pode não estar tão pequena assim.',
      'O problema não é só quanto você deve hoje.',
      'Tem dívida que cresce enquanto parece parada.',
    ],
    selectedHook: 'Tem dívida que cresce enquanto parece parada.',
    spokenText:
      'Tem dívida que cresce enquanto parece parada. Quando os juros são altos, esperar pode mudar bastante o valor final. Antes de pagar por impulso, compare juros, prazo e impacto no orçamento. Salve este vídeo e organize tudo no diagnóstico gratuito da Zafi.',
    ctas: [
      'Salve este vídeo e faça o diagnóstico gratuito da Zafi.',
      'Compare antes de decidir: organize suas dívidas na Zafi.',
    ],
    selectedCta: 'Salve este vídeo e faça o diagnóstico gratuito da Zafi.',
    caption:
      'O saldo de hoje não conta a história inteira. Compare juros, prazo e impacto no orçamento antes de decidir.',
    description:
      'Vídeo curto sobre dívidas de juros altos que podem crescer mesmo quando o valor inicial parece pequeno.',
    hashtags: ['#Dívida', '#Juros', '#Cartão', '#Dinheiro', '#Zafi'],
    thumbnailText: 'Ela cresce escondida',
    thumbnailUrls: [
      '/content-factory/oe-008/viral/thumbnail-a.svg',
      '/content-factory/oe-008/viral/thumbnail-b.svg',
      '/content-factory/oe-008/viral/thumbnail-c.svg',
    ],
    editStyles: ['Contador visual de juros', 'Cortes rápidos tipográficos'],
    scenes: [
      { kicker: 'ATENÇÃO', title: 'Ela parece parada.', body: 'Mas os juros continuam contando.', durationMs: 4500, treatment: 'signal' },
      { kicker: 'O SALDO DE HOJE', title: 'não é a história inteira', body: 'Prazo e taxa mudam o valor final.', durationMs: 4500, treatment: 'ink' },
      { kicker: 'ANTES DE PAGAR', title: 'Compare três coisas', body: 'Juros. Prazo. Impacto no orçamento.', durationMs: 5000, treatment: 'blue' },
      { kicker: 'SEM IMPULSO', title: 'Organize primeiro', body: 'Clareza reduz decisões apressadas.', durationMs: 4500, treatment: 'light' },
      { kicker: 'SALVE ESTE VÍDEO', title: 'Diagnóstico gratuito', body: 'meuzafi.com.br', durationMs: 5500, treatment: 'blue' },
    ],
    direction: {
      emotion: 'Alerta sem alarmismo',
      pace: 'Ágil, 155 palavras por minuto',
      pauses: 'Micro pausas antes das palavras juros, prazo e orçamento',
      framing: 'Close moderado com cortes tipográficos',
      expression: 'Curiosa no hook, segura na orientação',
      voice: 'Pt-BR neutra, energia controlada',
    },
    provider: { id: 'local-motion-v1', label: 'Zafi Motion Preview', generationTimeMs: 165, estimatedCostBrl: 0 },
    quality: { clarity: 94, retention: 96, branding: 91, cta: 91, spelling: 100, visual: 93, accessibility: 91 },
    compliance: { status: 'approved', findings: [], reviewedAt },
    trace: { researchId: 'oe008-research-003', briefId: 'oe008-brief-viral', scriptVersion: 1, assetVersion: 1 },
  },
  {
    id: 'oe014-primeira-campanha-v1',
    kind: 'educational',
    themeId: 'sobra-mes-no-fim-do-salario',
    title: 'Por que sobra mês no fim do salário?',
    topic: 'Falta de visibilidade sobre gastos fixos, variáveis e juros',
    objective: 'Gerar identificação imediata e levar ao diagnóstico gratuito da Zafi.',
    audience: 'Brasileiros que recebem renda mensal, mas perdem visibilidade do orçamento antes do fim do mês.',
    durationSeconds: 22,
    status: 'pending_approval',
    stage: 'pending_approval',
    score: 92,
    hooks: [
      'O salário cai. O mês continua.',
      'Você recebe todo mês. Então por que o dinheiro acaba antes?',
      'Não é falta de esforço. É falta de visão do todo.',
    ],
    selectedHook: 'O salário cai. O mês continua.',
    spokenText: 'Você recebe o salário. Então, por que o dinheiro acaba antes do mês? Isso nem sempre é falta de esforço. Quando contas fixas, gastos do dia a dia e juros ficam espalhados, você perde a visão do todo. A Zafi organiza sua vida financeira de forma simples. Quer entender para onde seu dinheiro está indo? Faça o diagnóstico gratuito.',
    ctas: [
      'Faça o diagnóstico financeiro gratuito da Zafi.',
      'Entenda para onde seu dinheiro está indo.',
    ],
    selectedCta: 'Faça o diagnóstico financeiro gratuito da Zafi.',
    caption: 'Quando contas fixas, gastos do dia a dia e juros ficam espalhados, fica difícil enxergar o todo. Organizar vem antes de cortar. Faça o diagnóstico financeiro gratuito da Zafi.',
    description: 'Primeira campanha oficial da Zafi sobre a sensação de o dinheiro terminar antes do mês.',
    hashtags: ['#Zafi', '#OrganizaçãoFinanceira', '#FinançasPessoais', '#Dinheiro', '#Dívidas'],
    thumbnailText: 'O dinheiro acaba antes do mês?',
    thumbnailUrls: [
      '/content-factory/oe-014/arte-estatica.png',
      '/content-factory/oe-014/carousel/slide-1.png',
      '/content-factory/oe-014/stories/story-1.png',
    ],
    editStyles: ['Editorial humano com cortes rápidos', 'B-roll financeiro com motion sutil'],
    scenes: [
      { kicker: 'VOCÊ JÁ SENTIU ISSO?', title: 'O salário cai. O mês continua.', body: 'E o dinheiro acaba antes.', durationMs: 2750, treatment: 'signal' },
      { kicker: 'A PERGUNTA', title: 'Para onde o dinheiro está indo?', body: 'Quando tudo fica espalhado, fica difícil enxergar.', durationMs: 2750, treatment: 'ink' },
      { kicker: 'SEM CULPA', title: 'Não é falta de esforço.', body: 'É falta de uma visão simples do todo.', durationMs: 2750, treatment: 'light' },
      { kicker: 'O QUE PESA', title: 'Fixos. Dia a dia. Juros.', body: 'Três forças disputando o mesmo salário.', durationMs: 2750, treatment: 'blue' },
      { kicker: 'ORGANIZE', title: 'Organizar vem antes de cortar.', body: 'Primeiro você entende. Depois decide.', durationMs: 2750, treatment: 'light' },
      { kicker: 'ZAFI', title: 'Sua vida financeira em um só lugar.', body: 'Diagnóstico simples, orientação clara.', durationMs: 2750, treatment: 'blue' },
      { kicker: 'PRÓXIMO PASSO', title: 'Descubra o que está pesando.', body: 'Sem promessa fácil. Sem julgamento.', durationMs: 2750, treatment: 'ink' },
      { kicker: 'DIAGNÓSTICO GRATUITO', title: 'Conheça a Zafi.', body: 'meuzafi.com.br', durationMs: 2750, treatment: 'blue' },
    ],
    direction: {
      emotion: 'Identificação e acolhimento sem culpa',
      pace: 'Ágil, com mudança visual a cada 2,75 segundos',
      pauses: 'Pausa curta após a pergunta inicial e antes do CTA',
      framing: 'Plano médio e B-roll superior, sempre em 9:16',
      expression: 'Natural, segura e próxima',
      voice: 'Pt-BR feminina, clara, com ritmo acelerado para 22 segundos',
    },
    provider: { id: 'local-premium-v1', label: 'Zafi Premium Studio · aprovação', generationTimeMs: 30000, estimatedCostBrl: 0 },
    quality: { clarity: 96, retention: 92, branding: 98, cta: 94, spelling: 100, visual: 93, accessibility: 91 },
    compliance: { status: 'approved', findings: [], reviewedAt: '2026-07-27T21:30:00-03:00' },
    trace: { researchId: 'oe014-benchmark-001', briefId: 'oe014-brief-v1', scriptVersion: 1, assetVersion: 1 },
    deliverables: {
      videoUrl: '/content-factory/oe-014/oe-014-primeira-campanha.mp4',
      carouselUrls: Array.from({ length: 7 }, (_, index) => `/content-factory/oe-014/carousel/slide-${index + 1}.png`),
      staticImageUrl: '/content-factory/oe-014/arte-estatica.png',
      storyUrls: Array.from({ length: 3 }, (_, index) => `/content-factory/oe-014/stories/story-${index + 1}.png`),
      publicationStatus: 'blocked_pending_ceo_approval',
    },
  },]
