import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import Breadcrumbs from '@/components/oraculo/Breadcrumbs'
import KnowledgeCard from '@/components/oraculo/KnowledgeCard'
import { categories, categoryMap, entries, SITE_URL, type CategorySlug } from '@/lib/oraculo'
export const generateStaticParams = () => categories.map(({ slug }) => ({ category: slug }))
export function generateMetadata({ params }: { params: { category: string } }): Metadata { const category = categoryMap[params.category as CategorySlug]; if (!category) return {}; const path = `/oraculo/${category.slug}`; return { title: `${category.name} — ORÁCULO | Zafi`, description: category.description, alternates: { canonical: path }, openGraph: { url: path, title: `${category.name} — ORÁCULO Zafi`, description: category.description } } }
export default function Page({ params }: { params: { category: string } }) {
  const category = categoryMap[params.category as CategorySlug]; if (!category) notFound(); const list = entries.filter((entry) => entry.category === category.slug); const url = `${SITE_URL}/oraculo/${category.slug}`
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'CollectionPage', name: `${category.name} — ORÁCULO`, url, hasPart: list.map((entry) => ({ '@type': 'Article', name: entry.title, url: `${url}/${entry.slug}` })) }, { '@type': 'BreadcrumbList', itemListElement: ['Zafi', 'ORÁCULO', category.name].map((name, index) => ({ '@type': 'ListItem', position: index + 1, name })) }] }
  return <main className="min-h-screen bg-[#f6f8fc] px-5 py-10"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><div className="mx-auto max-w-6xl"><Breadcrumbs items={[{ name: 'Zafi', href: '/' }, { name: 'ORÁCULO', href: '/oraculo' }, { name: category.name }]} /><div className="mt-12 grid gap-8 md:grid-cols-[1fr_16rem]"><div><span className="text-4xl">{category.icon}</span><h1 className="mt-4 text-4xl font-black">{category.name}</h1><p className="mt-4 text-lg text-slate-600">{category.description}</p></div><aside className="rounded-2xl bg-blue-50 p-5"><p className="text-3xl font-black text-blue-700">{list.length}</p><p className="text-sm font-bold">resposta{list.length === 1 ? '' : 's'} nesta categoria</p></aside></div><section className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{list.length ? list.map((entry) => <KnowledgeCard key={entry.slug} entry={entry} />) : <div className="rounded-2xl border border-dashed bg-white p-8"><h2 className="font-extrabold">Estante preparada para expansão</h2><p className="mt-2 text-sm text-slate-600">Novas respostas serão publicadas após pesquisa e revisão.</p></div>}</section><Link href="/oraculo" className="mt-12 inline-block font-bold text-blue-700">← Voltar ao ORÁCULO</Link></div></main>
}
