-- OE-016 — catálogo inicial: 30 peças completas, distintas e pendentes de aprovação humana.

insert into public.content_studio_categories(slug,label,sort_order) values
('educacao-financeira','Educação financeira',10),('renegociacao-dividas','Renegociação de dívidas',20),
('direitos-cuidados-consumidor','Direitos e cuidados do consumidor',30),('prevencao-golpes','Prevenção de golpes',40),
('planejamento-financeiro','Planejamento financeiro',50),('autoridade-marca','Autoridade da marca',60),
('conteudo-institucional','Conteúdo institucional',70),('diagnostico-financeiro','Diagnóstico financeiro',80),
('organizacao-priorizacao-dividas','Organização e priorização de dívidas',90);
insert into public.content_studio_networks(slug,label) values ('instagram','Instagram'),('facebook','Facebook'),('tiktok','TikTok');
insert into public.content_studio_formats(slug,label,width,height) values
('static_post','Post estático',1080,1350),('carousel','Carrossel',1080,1350),
('story','Story',1080,1920),('tiktok_image_sequence','Sequência de imagens',1080,1920);

do $$
#variable_conflict use_variable
declare
 s record; content_id uuid; version_id uuid; page_id uuid; category_id uuid; network_id uuid; format_id uuid;
 slide text; page_number integer; tag text;
begin
 for s in select * from (values
('salario-acaba-antes-do-mes','Por que sobra mês no fim do salário?','Dinheiro acabando antes do mês','Gerar identificação e incentivar clareza financeira.','educacao-financeira','instagram','carousel','O dinheiro acaba antes do mês?','Quando o dinheiro termina cedo, o primeiro passo não é se culpar. É enxergar o caminho dele. Separe despesas essenciais, compromissos e gastos variáveis. Clareza vem antes de qualquer corte.','ledger','Uma trilha visual transforma o mês em quatro blocos simples.',array['O dinheiro acaba antes do mês?','Não comece pela culpa.','Separe o essencial.','Enxergue compromissos e variáveis.','Clareza vem antes do corte.','Comece pelo diagnóstico da Zafi.']::text[]),
('gasto-fixo-ou-variavel','Gasto fixo ou variável?','Classificação de despesas','Ensinar uma organização simples do orçamento.','educacao-financeira','instagram','carousel','Fixo ou variável: onde seu dinheiro muda de rota','Gasto fixo se repete com pouca variação. Gasto variável muda conforme o uso e as escolhas do mês. Separar os dois ajuda a descobrir onde existe espaço real para ajustar, sem cortar o que é essencial.','split','Dois campos editoriais contrastantes organizam fixos e variáveis.',array['Fixo ou variável?','Fixo: se repete todo mês.','Variável: muda com uso e escolhas.','Essencial não é igual a fixo.','Organize antes de reduzir.']::text[]),
('reserva-mesmo-com-dividas','Reserva enquanto existem dívidas','Proteção contra imprevistos','Mostrar equilíbrio entre pagamento e proteção básica.','educacao-financeira','facebook','static_post','Dívida e imprevisto não marcam hora','Mesmo durante a organização das dívidas, uma pequena margem para imprevistos pode evitar novo endividamento. O valor depende da realidade de cada pessoa; comece com algo possível e sustentável.','calm','Uma margem de segurança aparece como espaço respirável, não como promessa.',array['Dívida e imprevisto não marcam hora']::text[]),
('parcela-menor-custo-maior','Parcela menor pode custar mais','Custo total de acordos','Ensinar a comparar prazo e valor final.','educacao-financeira','instagram','carousel','Parcela menor não significa acordo melhor','Alongar o prazo pode aliviar o mês e aumentar o custo final. Antes de aceitar, compare entrada, quantidade de parcelas, juros e valor total. A melhor proposta é a que cabe no orçamento e melhora o problema.','grid','Quatro números ocupam uma grade de comparação financeira.',array['Parcela menor não significa acordo melhor','Compare a entrada.','Confira o número de parcelas.','Pergunte pelos juros.','Olhe o valor total.','Escolha o que você consegue cumprir.']::text[]),
('uma-decisao-por-vez','Uma decisão financeira por vez','Redução da ansiedade','Ajudar o usuário a sair do modo de urgência.','educacao-financeira','facebook','static_post','Você não precisa resolver tudo hoje','Quando as contas se acumulam, tente escolher uma decisão possível para agora: listar dívidas, conferir um saldo ou calcular quanto cabe no mês. Movimento sustentável vale mais do que uma promessa impossível.','path','Um único caminho azul atravessa um fundo claro e calmo.',array['Você não precisa resolver tudo hoje']::text[]),
('vencimento-do-cartao','A data do cartão conversa com sua renda?','Planejamento de vencimentos','Mostrar o impacto de datas no fluxo de caixa.','educacao-financeira','instagram','story','A data do cartão ajuda ou aperta seu mês?','Concentrar vencimentos longe da entrada da renda pode criar pressão desnecessária. Revise as datas disponíveis nos canais oficiais e escolha uma organização que facilite o controle.','signal','Calendário limpo com uma data destacada em azul.',array['A data do cartão ajuda ou aperta seu mês?']::text[]),
('orcamento-que-cabe-na-vida','Um orçamento que cabe na vida','Planejamento realista','Combater planos financeiros impossíveis.','educacao-financeira','tiktok','tiktok_image_sequence','Orçamento bom não é o mais rígido','Um orçamento só funciona quando reconhece moradia, alimentação, transporte, saúde e a vida real. Metas impossíveis geram abandono. Comece pelo que é sustentável e ajuste com o tempo.','calm','Camadas de despesas formam uma composição humana e respirável.',array['Orçamento bom não é o mais rígido','Proteja o essencial.','Reserve espaço para a vida real.','Defina uma meta possível.','Revise sem culpa.']::text[]),
('juros-nao-esperam','Juros não esperam o próximo mês','Crescimento da dívida','Incentivar diagnóstico sem criar pânico.','educacao-financeira','instagram','carousel','Juros não esperam você se organizar','Algumas dívidas crescem mais rápido do que outras. Descobrir taxa, encargos e saldo atualizado ajuda a definir prioridade. Informação reduz a urgência e melhora a negociação.','signal','Uma linha crescente é interrompida por um ponto de clareza.',array['Juros não esperam você se organizar','Descubra o saldo atualizado.','Confira juros e encargos.','Compare quais dívidas crescem mais.','Defina a prioridade com informação.']::text[]),
('recomecar-apos-imprevisto','Recomeçar depois de um imprevisto','Retomada financeira','Acolher quem perdeu o planejamento.','educacao-financeira','facebook','static_post','Seu plano falhou. Você não falhou.','Um imprevisto pode desmontar o orçamento sem apagar todo o progresso. Atualize os números, proteja o essencial e construa um próximo passo menor. Planejamento também é saber recomeçar.','calm','Blocos deslocados voltam a se alinhar em uma composição serena.',array['Seu plano falhou. Você não falhou.']::text[]),
('tres-numeros-para-comecar','Três números para começar','Primeiro diagnóstico','Ensinar o mínimo necessário para ganhar clareza.','educacao-financeira','instagram','carousel','Comece por três números','Você não precisa de uma planilha complexa para começar. Saiba quanto entra, quanto custa o essencial e quanto está comprometido com dívidas. Esses três números já mudam a qualidade da próxima decisão.','ledger','Três números grandes funcionam como marcos de uma prova financeira.',array['Comece por três números','1. Quanto entra.','2. Quanto custa o essencial.','3. Quanto vai para dívidas.','Agora escolha o próximo passo.']::text[]),
('liste-todas-as-dividas','Liste antes de negociar','Mapa das dívidas','Transformar confusão em inventário acionável.','organizacao-priorizacao-dividas','instagram','carousel','A dívida que você não vê decide por você','Liste credor, saldo, parcela, atraso e tipo de dívida. O objetivo não é pagar tudo hoje; é enxergar o cenário completo para definir uma ordem possível.','grid','Cartões de dívida aparecem como fichas organizadas, sem logos de parceiros.',array['A dívida que você não vê decide por você','Anote o credor.','Registre saldo e atraso.','Separe parcela e juros.','Depois defina a ordem.']::text[]),
('qual-divida-pagar-primeiro','Qual dívida pagar primeiro?','Priorização de dívidas','Levar o usuário ao diagnóstico gratuito.','organizacao-priorizacao-dividas','tiktok','tiktok_image_sequence','Qual dívida merece sua atenção primeiro?','A resposta depende do risco, do custo e do impacto na sua vida. Proteja despesas essenciais, identifique dívidas que crescem rápido e compare consequências. O diagnóstico da Zafi ajuda a organizar essa ordem.','path','Três rotas convergem para uma prioridade marcada.',array['Qual dívida pagar primeiro?','Proteja o essencial.','Veja qual cresce mais rápido.','Considere o impacto do atraso.','Monte uma ordem possível.']::text[]),
('prepare-uma-negociacao','Prepare-se antes de negociar','Roteiro de negociação','Ajudar o usuário a entrar em uma negociação com limite claro.','renegociacao-dividas','instagram','carousel','Não negocie antes de saber seu limite','Antes do contato, defina entrada e parcela máximas. Durante a conversa, peça saldo, prazo, juros e custo total. Aceite apenas uma condição que você consegue manter.','split','De um lado o limite pessoal; do outro, os dados da proposta.',array['Não negocie antes de saber seu limite','Defina a entrada máxima.','Defina a parcela máxima.','Peça o custo total.','Confirme tudo por escrito.']::text[]),
('parcela-nao-cabe','A parcela não cabe','Renegociação sustentável','Normalizar a contraproposta responsável.','renegociacao-dividas','facebook','static_post','Se a parcela não cabe, o acordo ainda não resolveu','Aceitar uma parcela impossível costuma apenas adiar o problema. Refaça o orçamento e peça outra condição. Um acordo sustentável precisa respeitar despesas essenciais e imprevistos.','signal','Uma parcela ultrapassa o limite visual e é reposicionada dentro dele.',array['Se a parcela não cabe, o acordo ainda não resolveu']::text[]),
('compare-propostas','Compare propostas sem olhar só o desconto','Análise de acordos','Ensinar critérios de comparação.','renegociacao-dividas','instagram','carousel','O maior desconto nem sempre é o melhor acordo','Compare entrada, parcela, prazo, juros, custo final e consequências em caso de atraso. O acordo certo é aquele que reduz o problema e pode ser cumprido até o fim.','grid','Seis critérios formam uma ficha de comparação limpa.',array['O maior desconto nem sempre é o melhor acordo','Entrada','Parcela','Prazo','Juros e custo final','O que acontece se atrasar?']::text[]),
('credito-para-pagar-divida','Crédito novo para pagar dívida','Troca de dívida','Explicar quando a troca pode piorar.','renegociacao-dividas','facebook','carousel','Trocar uma dívida só ajuda quando o custo cai','Crédito novo não é solução automática. Compare o custo total, o prazo e a parcela. Se a nova dívida for mais cara ou não couber no orçamento, o problema apenas muda de nome.','split','Duas dívidas são comparadas lado a lado com custo e prazo.',array['Crédito novo resolve?','Só quando reduz o custo total.','A parcela precisa caber.','O prazo também importa.','Compare antes de trocar.']::text[]),
('sair-do-rotativo','Como sair do rotativo do cartão','Dívida de cartão','Incentivar ação organizada diante de juros altos.','renegociacao-dividas','instagram','carousel','O rotativo transforma tempo em dívida','Interrompa novas compras no cartão negociado, peça o saldo atualizado e compare parcelamento, juros e custo total. Crédito novo só ajuda quando for comprovadamente mais barato.','ledger','Uma fatura se transforma em linha do tempo de decisão.',array['O rotativo transforma tempo em dívida','Pare de aumentar o saldo.','Peça o valor atualizado.','Compare parcelamento e juros.','Só troque se o custo cair.']::text[]),
('guarde-comprovantes','Depois do acordo, guarde tudo','Acompanhamento de acordo','Reforçar organização após a negociação.','direitos-cuidados-consumidor','facebook','static_post','A negociação termina. A comprovação fica.','Guarde proposta, contrato, boletos e comprovantes. Acompanhe a atualização da dívida e use canais oficiais se houver divergência. Organização também protege você depois do pagamento.','grid','Documentos aparecem como camadas numeradas de auditoria.',array['A negociação termina. A comprovação fica.']::text[]),
('taxa-antecipada','Taxa antecipada para liberar crédito','Prevenção de golpe','Alertar sem alarmismo e direcionar a canais oficiais.','prevencao-golpes','instagram','carousel','Pediram depósito para liberar crédito? Pare.','O Banco Central alerta que nenhuma instituição pode exigir depósito antecipado para liberar empréstimo. Não pague, não envie senha e confirme a empresa em canais oficiais. Fonte: Banco Central do Brasil, consulta em 31/07/2026.','signal','Faixa amarela de alerta com passos curtos e sem imagens de pessoas.',array['Pediram depósito para liberar crédito? Pare.','Não faça o pagamento.','Não compartilhe senha.','Confirme a instituição.','Use apenas canais oficiais.']::text[]),
('confirme-o-canal','Confirme o canal antes de negociar','Segurança digital','Reduzir risco de links e contatos falsos.','prevencao-golpes','tiktok','tiktok_image_sequence','O link parece verdadeiro. Isso não basta.','Antes de informar dados ou pagar, confira o domínio, procure o canal oficial por conta própria e confirme o beneficiário. Não use o senso de urgência de uma mensagem como prova de legitimidade.','signal','Um endereço é examinado por marcadores de domínio, conexão e beneficiário.',array['O link parece verdadeiro. Isso não basta.','Confira o domínio.','Procure o canal oficial.','Confirme o beneficiário.','Não decida sob pressão.']::text[]),
('urgencia-artificial','Golpes usam pressa','Urgência artificial','Ensinar um sinal recorrente de fraude.','prevencao-golpes','instagram','story','Pressa demais é sinal para parar','Mensagens que exigem pagamento imediato, ameaçam perder uma oportunidade ou impedem você de conferir dados merecem cautela. Pare, valide o contato e só continue em um canal oficial.','signal','Cronômetro abstrato é interrompido por uma área de verificação.',array['Pressa demais é sinal para parar']::text[]),
('proteja-seus-dados','Seus dados também têm valor','Proteção de dados','Orientar sobre compartilhamento responsável.','prevencao-golpes','facebook','static_post','Senha e código de confirmação não são dados de negociação','Não compartilhe senha, token ou código recebido por SMS. Empresas legítimas não precisam desses dados para apresentar uma proposta. Em caso de dúvida, encerre o contato e procure o canal oficial.','split','Dados seguros e dados que nunca devem ser compartilhados ficam separados.',array['Senha e código de confirmação não são dados de negociação']::text[]),
('como-a-zafi-ajuda','Como a Zafi ajuda','Proposta de valor','Explicar o produto sem parecer publicidade.','conteudo-institucional','instagram','carousel','A Zafi começa pelo seu problema, não pela oferta','Você organiza sua situação, recebe um diagnóstico, entende prioridades e visualiza recomendações explicadas. Parceiros podem aparecer como consequência da análise, nunca como propaganda disfarçada.','path','A jornada do usuário aparece como uma sequência de clareza até ação.',array['A Zafi começa pelo seu problema','1. Organize sua situação.','2. Receba um diagnóstico.','3. Entenda prioridades.','4. Compare caminhos explicados.']::text[]),
('nao-somos-vitrine','A Zafi não é uma vitrine de links','Posicionamento da marca','Fortalecer autoridade e confiança.','autoridade-marca','facebook','static_post','Orientação primeiro. Parceiros depois.','A Zafi foi construída para ajudar você a entender a situação e escolher um próximo passo. Quando um parceiro aparece, a recomendação deve ter motivo, contexto e rastreabilidade.','split','A orientação ocupa o primeiro plano; ofertas ficam em plano secundário.',array['Orientação primeiro. Parceiros depois.']::text[]),
('recomendacao-explicada','Por que essa recomendação apareceu?','Recomendação explicável','Mostrar transparência do motor da Zafi.','autoridade-marca','instagram','carousel','Toda recomendação da Zafi precisa explicar o porquê','O motor considera o contexto informado, filtra opções inelegíveis e registra os motivos usados. A Zafi não deve esconder regra comercial dentro de uma resposta financeira.','grid','Critérios, filtro e motivo aparecem como etapas auditáveis.',array['Por que essa recomendação apareceu?','Seu contexto inicia a análise.','Opções inelegíveis são filtradas.','Critérios são aplicados.','O motivo fica registrado.']::text[]),
('diagnostico-gratuito','Diagnóstico financeiro gratuito','Convite institucional','Levar novos usuários ao produto com clareza.','conteudo-institucional','instagram','story','Clareza financeira começa com um diagnóstico','Organize suas dívidas, entenda prioridades e descubra um próximo passo possível. O diagnóstico financeiro da Zafi é gratuito e não promete crédito, desconto ou resultado garantido.','calm','O CTA surge em uma superfície clara com marca e espaço generoso.',array['Clareza financeira começa com um diagnóstico']::text[]),
('o-que-a-zafi-pergunta','O que a Zafi pergunta no diagnóstico','Transparência da coleta','Reduzir receio antes do início do fluxo.','diagnostico-financeiro','tiktok','tiktok_image_sequence','A Zafi não precisa saber tudo de uma vez','A coleta é progressiva. Cada informação deve ter uma finalidade clara: personalizar orientação, registrar consentimento, medir a jornada ou atender uma obrigação. Você avança por etapas.','path','Campos aparecem progressivamente, um por tela, com finalidade visível.',array['A Zafi não precisa saber tudo de uma vez','A coleta é progressiva.','Cada campo tem uma finalidade.','Sua jornada é registrada por etapas.','Clareza sem formulário interminável.']::text[]),
('plano-financeiro-30-dias','Um plano financeiro para os próximos 30 dias','Planejamento de curto prazo','Transformar diagnóstico em execução simples.','planejamento-financeiro','instagram','carousel','Não planeje o ano antes de organizar o próximo mês','Nos próximos 30 dias, proteja o essencial, liste dívidas, escolha uma prioridade e acompanhe o que mudou. Um ciclo curto gera informação para o plano seguinte.','ledger','Quatro semanas viram marcos simples de acompanhamento.',array['Organize os próximos 30 dias','Semana 1: proteja o essencial.','Semana 2: liste as dívidas.','Semana 3: escolha uma prioridade.','Semana 4: revise o que mudou.']::text[]),
('diagnostico-e-o-inicio','Diagnóstico não é sentença','Papel do diagnóstico','Mostrar o diagnóstico como começo da jornada.','diagnostico-financeiro','facebook','static_post','Diagnóstico é ponto de partida, não sentença','Sua situação financeira pode mudar. O diagnóstico organiza o momento atual e ajuda a escolher um próximo passo. Depois, novos dados e decisões atualizam o plano.','calm','Um ponto inicial azul abre caminhos, sem rótulos negativos.',array['Diagnóstico é ponto de partida, não sentença']::text[]),
('prioridade-sem-culpa','Organize dívidas sem culpa','Priorização responsável','Unir acolhimento e ação prática.','organizacao-priorizacao-dividas','instagram','carousel','Prioridade financeira não é julgamento','Comece pelo que ameaça o essencial, cresce mais rápido ou causa maior impacto. Sua ordem pode ser diferente da ordem de outra pessoa. O objetivo é construir um plano que você consegue cumprir.','path','Três critérios se encontram em uma decisão pessoal, sem ranking moral.',array['Prioridade financeira não é julgamento','Proteja o essencial.','Observe o custo.','Considere o impacto.','Escolha uma ordem possível.']::text[])
 ) as seed(slug,internal_title,theme,objective,category_slug,network_slug,format_slug,art_text,caption,design_variant,visual_direction,slides)
 loop
  select id into category_id from public.content_studio_categories where slug=s.category_slug;
  select id into network_id from public.content_studio_networks where slug=s.network_slug;
  select id into format_id from public.content_studio_formats where slug=s.format_slug;
  insert into public.content_studio_contents(slug,internal_title,theme,objective,category_id,network_id,format_id,status,created_by)
  values(s.slug,s.internal_title,s.theme,s.objective,category_id,network_id,format_id,'pending_review','Editor Chief + Content Studio') returning id into content_id;
  tag:=case s.category_slug when 'prevencao-golpes' then '#SegurançaFinanceira' when 'renegociacao-dividas' then '#RenegociaçãoDeDívidas' when 'diagnostico-financeiro' then '#DiagnósticoFinanceiro' else '#EducaçãoFinanceira' end;
  insert into public.content_studio_content_versions(content_id,version_number,status,art_text,caption,cta,hashtags,sources,visual_direction,design_variant,author_name,author_type,change_summary)
  values(content_id,1,'pending_review',s.art_text,s.caption,'Faça seu diagnóstico financeiro gratuito em meuzafi.com.br.',array['#Zafi',tag,'#VidaFinanceira','#OrganizaçãoFinanceira'],
   case when s.slug='taxa-antecipada' then '[{"title":"BC alerta sobre depósito prévio","publisher":"Banco Central do Brasil","url":"https://www.bcb.gov.br/detalhenoticia/15352/nota","consulted_at":"2026-07-31"}]'::jsonb else '[]'::jsonb end,
   s.visual_direction,s.design_variant,'Content Studio Agent','agent','Conteúdo inicial da OE-016 preparado para aprovação humana.') returning id into version_id;
  update public.content_studio_contents set current_version_id=version_id where id=content_id;
  page_number:=0;
  foreach slide in array s.slides loop
   page_number:=page_number+1;
   insert into public.content_studio_pages(content_id,version_id,page_number,art_text,alt_text,visual_direction)
   values(content_id,version_id,page_number,slide,format('Peça Zafi “%s”, página %s: %s',s.internal_title,page_number,slide),s.visual_direction) returning id into page_id;
   insert into public.content_studio_files(content_id,version_id,page_id,asset_kind,mime_type,file_name,asset_path)
   values(content_id,version_id,page_id,'image','image/png',format('zafi_%s_v1_p%s.png',s.slug,page_number),format('/admin/content-studio/assets/%s/%s',version_id,page_number));
  end loop;
  insert into public.content_studio_audit_events(content_id,version_id,event_type,actor_name,actor_role,payload)
  values(content_id,version_id,'content_created','Content Studio Agent','agent',jsonb_build_object('version',1,'status','pending_review','network',s.network_slug,'format',s.format_slug));
 end loop;
end $$;

do $$
#variable_conflict use_variable
declare order_id uuid; revision_id uuid; version integer;
begin
 insert into public.executive_orders(oe_code) values('OE-016') on conflict(oe_code) do nothing;
 select id into order_id from public.executive_orders where oe_code='OE-016';
 select coalesce(max(r.version),0)+1 into version from public.executive_order_revisions r where r.order_id=order_id;
 insert into public.executive_order_revisions(order_id,version,title,description,priority,status,author_name,author_email,author_role,change_reason)
 values(order_id,version,'Zafi Content Studio','Criar dentro do admin um único setor para gerar, revisar, aprovar, reprovar, refazer, versionar e exportar conteúdos de Instagram, Facebook e TikTok, sem publicação automática.','high','in_progress','Conselho Estratégico','conselho@meuzafi.com.br','council','Ordem recebida sem numeração e registrada como próxima sequência, OE-016.') returning id into revision_id;
 insert into public.executive_order_audit_events(order_id,event_type,actor_name,actor_email,actor_role,entity_type,entity_id,payload)
 values(order_id,'order_created','Conselho Estratégico','conselho@meuzafi.com.br','council','order_revision',revision_id,jsonb_build_object('oe_code','OE-016','priority','high','automatic_publication',false,'initial_contents',30));
end $$;
